<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-076B1A2F" name="Validating the course title" tests="1" failures="0" timestamp="1 Nov 2020 10:52:44 GMT" time="0.111" errors="0">
  <testcase name="@BeforeTest setUp" time="0.0" classname="testcases.ValidateCourseTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at testBase.Base.initializeDriver(Base.java:51)
	at testcases.ValidateCourseTest.setUp(ValidateCourseTest.java:28)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeTest setUp -->
  <testcase name="@AfterTest tearDown" time="0.0" classname="testcases.ValidateCourseTest">
    <skipped/>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase name="validateCourse" time="0.07" classname="testcases.ValidateCourseTest">
    <skipped/>
  </testcase> <!-- validateCourse -->
</testsuite> <!-- Validating the course title -->
